# Generated by Django 3.1.1 on 2020-10-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a_table',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='s_table',
            fields=[
                ('s_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dex_id', models.IntegerField(default=0)),
                ('gen', models.IntegerField(default=0)),
                ('gender_rate', models.IntegerField(default=0)),
                ('capture_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_table',
            fields=[
                ('t_name', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('t_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Normal', models.FloatField(default=0)),
                ('Fire', models.FloatField(default=0)),
                ('Water', models.FloatField(default=0)),
                ('Grass', models.FloatField(default=0)),
                ('Flying', models.FloatField(default=0)),
                ('Fighting', models.FloatField(default=0)),
                ('Poison', models.FloatField(default=0)),
                ('Electric', models.FloatField(default=0)),
                ('Ground', models.FloatField(default=0)),
                ('Rock', models.FloatField(default=0)),
                ('Psychic', models.FloatField(default=0)),
                ('Ice', models.FloatField(default=0)),
                ('Bug', models.FloatField(default=0)),
                ('Ghost', models.FloatField(default=0)),
                ('Steel', models.FloatField(default=0)),
                ('Dragon', models.FloatField(default=0)),
                ('Dark', models.FloatField(default=0)),
                ('Fairy', models.FloatField(default=0)),
                ('t', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokewiki.t_table')),
            ],
        ),
        migrations.CreateModel(
            name='f_table',
            fields=[
                ('f_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
                ('df', models.IntegerField(default=0)),
                ('spatk', models.IntegerField(default=0)),
                ('spdf', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('type1', models.CharField(default='', max_length=10)),
                ('type2', models.CharField(default='', max_length=10)),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokewiki.s_table')),
            ],
        ),
        migrations.CreateModel(
            name='a_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokewiki.a_table')),
                ('f_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokewiki.f_table')),
            ],
        ),
    ]
