# Generated by Django 3.1.1 on 2020-10-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_table',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gen', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
                ('spatk', models.IntegerField(default=0)),
                ('df', models.IntegerField(default=0)),
                ('spdf', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('rarity', models.IntegerField(default=0)),
            ],
        ),
    ]
