# Generated by Django 3.1.1 on 2020-10-14 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(default='', max_length=10)),
                ('t2', models.CharField(default='', max_length=10)),
                ('s_factor', models.FloatField(default=0)),
                ('week_factor', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_table',
            fields=[
                ('t_name', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='p_table',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gen', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
                ('spatk', models.IntegerField(default=0)),
                ('df', models.IntegerField(default=0)),
                ('spdf', models.IntegerField(default=0)),
                ('spd', models.IntegerField(default=0)),
                ('rarity', models.IntegerField(default=0)),
                ('type1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='pokewiki.t_table')),
                ('type2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='pokewiki.t_table')),
            ],
        ),
    ]
