# Generated by Django 3.1.1 on 2020-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_table',
            name='capture_rate',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='s_table',
            name='gender_rate',
            field=models.IntegerField(default=None),
        ),
    ]
