# Generated by Django 3.1.1 on 2020-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0002_auto_20201020_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_table',
            name='capture_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='s_table',
            name='gender_rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
