# Generated by Django 3.1.1 on 2020-10-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0002_auto_20201017_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_table',
            name='t_id',
            field=models.IntegerField(default=0),
        ),
    ]
