# Generated by Django 3.1.1 on 2020-10-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0003_t_table_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_table',
            name='base_happiness',
        ),
    ]
