# Generated by Django 3.1.1 on 2020-10-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0004_remove_p_table_base_happiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_table',
            name='type1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='p_table',
            name='type2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
