# Generated by Django 3.1.1 on 2020-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0004_auto_20201020_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_relation',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
