# Generated by Django 3.1.1 on 2020-10-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0005_auto_20201017_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_relation',
            name='t',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokewiki.t_table'),
        ),
    ]
