# Generated by Django 3.1.1 on 2020-10-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0006_m_relation_m_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_table',
            name='gen',
            field=models.IntegerField(default=0),
        ),
    ]
