# Generated by Django 3.1.1 on 2020-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0006_auto_20201018_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_table',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
