# Generated by Django 3.1.1 on 2020-10-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0007_a_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_table',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
