# Generated by Django 3.1.1 on 2020-10-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0007_m_table_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_table',
            name='accuaracy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='m_table',
            name='dmg_class',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='m_table',
            name='effect',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='m_table',
            name='gen',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='m_table',
            name='types',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
