# Generated by Django 3.1.1 on 2020-10-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0008_auto_20201024_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_table',
            name='effect',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
    ]
