# Generated by Django 3.1.1 on 2020-10-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0009_auto_20201024_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_table',
            name='effect',
            field=models.CharField(default='', max_length=3500, null=True),
        ),
    ]
