# Generated by Django 3.1.1 on 2020-10-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0011_auto_20201024_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_table',
            name='m_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
