# Generated by Django 3.1.1 on 2020-10-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0012_auto_20201024_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_table',
            name='pp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
