# Generated by Django 3.1.1 on 2020-10-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0013_auto_20201024_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_relation',
            name='learn_method',
        ),
        migrations.RemoveField(
            model_name='m_relation',
            name='level_learned',
        ),
    ]
