# Generated by Django 3.1.1 on 2020-10-25 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0014_auto_20201025_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_relation',
            name='s_name',
        ),
        migrations.AddField(
            model_name='m_relation',
            name='f_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pokewiki.f_table'),
        ),
        migrations.AlterField(
            model_name='m_relation',
            name='m_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pokewiki.m_table'),
        ),
    ]
