# Generated by Django 3.1.1 on 2020-11-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokewiki', '0015_auto_20201025_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='i_table',
            fields=[
                ('i_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('i_name', models.CharField(default='', max_length=50, null=True)),
                ('cost', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(default='', max_length=50, null=True)),
                ('effect', models.CharField(default='', max_length=5000, null=True)),
            ],
        ),
    ]
