# Generated by Django 3.1.1 on 2020-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_table',
            name='fav_poke',
        ),
        migrations.AddField(
            model_name='profile_table',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='team_table',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
