# Generated by Django 3.1.1 on 2020-10-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201027_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_table',
            old_name='username',
            new_name='user',
        ),
    ]
