# Generated by Django 3.1.1 on 2020-10-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201027_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_table',
            name='team_code',
        ),
        migrations.AddField(
            model_name='team_table',
            name='team_comp',
            field=models.JSONField(null=True),
        ),
    ]
