# Generated by Django 3.1.1 on 2020-10-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201027_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_table',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
