# Generated by Django 3.1.1 on 2020-11-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201029_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_table',
            name='image',
        ),
    ]
